### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by syddm** [VideoGuys/python-client#2]
I had to do a new system install, and with it newer version of videoguys. Right now, package is not working. It's using simple_rest_client. Before, in the old install I had simple_rest_client-0.5.4.dist-info, and video guys was working with it. But now active version is simple_rest_client-1.0.5.dist-info, and this version is not using aiohttp anymore it's using httpx, and now starting a upload throws 
  File "/home/.local/lib/python3.6/site-packages/videoguys/clients/api.py", line 189, in uploadVideo
    raise ValueError("invalid upload code or filepath specified")
ValueError: invalid upload code or filepath specified
And if you comment out the error, it goes further in:

Traceback (most recent call last):
  File "/home/.local/lib/python3.6/site-packages/simple_rest_client/decorators.py", line 28, in wrapper
    response = f(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/simple_rest_client/request.py", line 25, in make_request
    client_response = client_method(request.url, **client_options)
  File "/home/.local/lib/python3.6/site-packages/httpx/_client.py", line 786, in post
    timeout=timeout,
  File "/home/.local/lib/python3.6/site-packages/httpx/_client.py", line 568, in request
    cookies=cookies,
  File "/home/.local/lib/python3.6/site-packages/httpx/_client.py", line 210, in build_request
    cookies=cookies,
  File "/home/.local/lib/python3.6/site-packages/httpx/_models.py", line 614, in __init__
    self.stream = encode(data, files, json)
  File "/home/.local/lib/python3.6/site-packages/httpx/_content_streams.py", line 335, in encode
    return MultipartStream(data=data, files=files, boundary=boundary)
  File "/home/.local/lib/python3.6/site-packages/httpx/_content_streams.py", line 278, in __init__
    for field in self.iter_fields(data, files):
  File "/home/.local/lib/python3.6/site-packages/httpx/_content_streams.py", line 299, in iter_fields
    yield self.DataField(name=name, value=value)
  File "/home/.local/lib/python3.6/site-packages/httpx/_content_streams.py", line 206, in __init__
    raise TypeError("Invalid type for value. Expected str or bytes.")
TypeError: Invalid type for value. Expected str or bytes.

I manually copied older version of simple_rest_client, and with I can use videoguys package, but obviously iy would be better if it worked properly without manual user intervention.

**Comment by VideoGuys** [comment]
Thanks for bringing this to my attention, I will close this issue once a fix has been released.

**Comment by VideoGuys** [comment]
this has been fixed in a recent [commit](https://github.com/VideoGuys/python-client/commit/93d6d7e2f2414e0953dd19a4058d90b5335e9fe8)
